#ifndef NPC_H
#define NPC_H

#include "ompcapi.h"
#include <stdbool.h>
#include <stdint.h>

bool NPC_Connect(const char *name, const char *script);
void *NPC_Create(const char *name, int *id);
bool NPC_Destroy(void *npc);
void *NPC_FromID(int npcid);
int NPC_GetID(void *npc);
bool NPC_IsValid(void *npc);
void *NPC_GetPlayer(void *npc);
bool NPC_Spawn(void *npc);
bool NPC_Respawn(void *npc);
bool NPC_SetPos(void *npc, float x, float y, float z);
bool NPC_GetPos(void *npc, float *x, float *y, float *z);
bool NPC_SetRot(void *npc, float rx, float ry, float rz);
bool NPC_GetRot(void *npc, float *rx, float *ry, float *rz);
bool NPC_SetFacingAngle(void *npc, float angle);
bool NPC_GetFacingAngle(void *npc, float *angle);
bool NPC_SetVirtualWorld(void *npc, int virtualWorld);
int NPC_GetVirtualWorld(void *npc);
bool NPC_SetInterior(void *npc, int interior);
int NPC_GetInterior(void *npc);
bool NPC_Move(void *npc, float x, float y, float z, int moveType, float moveSpeed, float stopRange);
bool NPC_MoveToPlayer(void *npc, void *player, int moveType, float moveSpeed, float stopRange, int posCheckUpdateDelay, bool autoRestart);
bool NPC_StopMove(void *npc);
bool NPC_IsMoving(void *npc);
bool NPC_SetSkin(void *npc, int model);
bool NPC_IsStreamedIn(void *npc, void *player);
bool NPC_IsAnyStreamedIn(void *npc);
int NPC_GetAll(int *npcsArr, int maxNPCs);
bool NPC_SetHealth(void *npc, float health);
float NPC_GetHealth(void *npc);
bool NPC_SetArmour(void *npc, float armour);
float NPC_GetArmour(void *npc);
bool NPC_IsDead(void *npc);
bool NPC_SetInvulnerable(void *npc, bool toggle);
bool NPC_IsInvulnerable(void *npc);
bool NPC_SetWeapon(void *npc, uint8_t weapon);
uint8_t NPC_GetWeapon(void *npc);
bool NPC_SetAmmo(void *npc, int ammo);
int NPC_GetAmmo(void *npc);
bool NPC_SetAmmoInClip(void *npc, int ammo);
int NPC_GetAmmoInClip(void *npc);
bool NPC_EnableReloading(void *npc, bool enable);
bool NPC_IsReloadEnabled(void *npc);
bool NPC_IsReloading(void *npc);
bool NPC_EnableInfiniteAmmo(void *npc, bool enable);
bool NPC_IsInfiniteAmmoEnabled(void *npc);
int NPC_GetWeaponState(void *npc);
bool NPC_SetKeys(void *npc, uint16_t upAndDown, uint16_t leftAndRight, uint16_t keys);
bool NPC_GetKeys(void *npc, uint16_t *upAndDown, uint16_t *leftAndRight, uint16_t *keys);
bool NPC_SetWeaponSkillLevel(void *npc, uint8_t skill, int level);
int NPC_GetWeaponSkillLevel(void *npc, int skill);
bool NPC_MeleeAttack(void *npc, int time, bool secondaryAttack);
bool NPC_StopMeleeAttack(void *npc);
bool NPC_IsMeleeAttacking(void *npc);
bool NPC_SetFightingStyle(void *npc, int style);
int NPC_GetFightingStyle(void *npc);
bool NPC_Shoot(void *npc, uint8_t weapon, int hitId, int hitType, float endX, float endY, float endZ, float offsetX, float offsetY, float offsetZ, bool isHit, uint8_t checkInBetweenFlags);
bool NPC_IsShooting(void *npc);
bool NPC_AimAt(void *npc, float x, float y, float z, bool shoot, int shootDelay, bool updateAngle, float offsetFromX, float offsetFromY, float offsetFromZ, uint8_t checkInBetweenFlags);
bool NPC_AimAtPlayer(void *npc, void *atPlayer, bool shoot, int shootDelay, bool updateAngle, float offsetX, float offsetY, float offsetZ, float offsetFromX, float offsetFromY, float offsetFromZ, uint8_t checkInBetweenFlags);
bool NPC_StopAim(void *npc);
bool NPC_IsAiming(void *npc);
bool NPC_IsAimingAtPlayer(void *npc, void *atPlayer);
bool NPC_SetWeaponAccuracy(void *npc, int weapon, float accuracy);
float NPC_GetWeaponAccuracy(void *npc, int weapon);
bool NPC_SetWeaponReloadTime(void *npc, int weapon, int time);
int NPC_GetWeaponReloadTime(void *npc, int weapon);
int NPC_GetWeaponActualReloadTime(void *npc, int weapon);
bool NPC_SetWeaponShootTime(void *npc, int weapon, int time);
int NPC_GetWeaponShootTime(void *npc, int weapon);
bool NPC_SetWeaponClipSize(void *npc, int weapon, int size);
int NPC_GetWeaponClipSize(void *npc, int weapon);
int NPC_GetWeaponActualClipSize(void *npc, int weapon);
bool NPC_EnterVehicle(void *npc, void *vehicle, int seatId, int moveType);
bool NPC_ExitVehicle(void *npc);
bool NPC_PutInVehicle(void *npc, void *vehicle, int seatId);
bool NPC_RemoveFromVehicle(void *npc);
void *NPC_GetVehicle(void *npc);
int NPC_GetVehicleID(void *npc);
void *NPC_GetEnteringVehicle(void *npc);
int NPC_GetEnteringVehicleID(void *npc);
int NPC_GetVehicleSeat(void *npc);
int NPC_GetEnteringVehicleSeat(void *npc);
bool NPC_IsEnteringVehicle(void *npc);
bool NPC_UseVehicleSiren(void *npc, bool use);
bool NPC_IsVehicleSirenUsed(void *npc);
bool NPC_SetVehicleHealth(void *npc, float health);
float NPC_GetVehicleHealth(void *npc);
bool NPC_SetVehicleHydraThrusters(void *npc, int direction);
int NPC_GetVehicleHydraThrusters(void *npc);
bool NPC_SetVehicleGearState(void *npc, int gearState);
int NPC_GetVehicleGearState(void *npc);
bool NPC_SetVehicleTrainSpeed(void *npc, float speed);
float NPC_GetVehicleTrainSpeed(void *npc);
int NPC_CreatePath();
bool NPC_DestroyPath(int pathId);
bool NPC_DestroyAllPath();
int NPC_GetPathCount();
bool NPC_AddPointToPath(int pathId, float x, float y, float z, float stopRange);
bool NPC_RemovePointFromPath(int pathId, int pointIndex);
bool NPC_ClearPath(int pathId);
int NPC_GetPathPointCount(int pathId);
bool NPC_GetPathPoint(int pathId, int pointIndex, float *x, float *y, float *z, float *stopRange);
int NPC_GetCurrentPathPointIndex(void *npc);
bool NPC_IsValidPath(int pathId);
bool NPC_HasPathPointInRange(int pathId, float x, float y, float z, float radius);
bool NPC_MoveByPath(void *npc, int pathId, int moveType, float moveSpeed, bool reverse);
bool NPC_ResetAnimation(void *npc);
bool NPC_SetAnimation(void *npc, int animationId, float delta, bool loop, bool lockX, bool lockY, bool freeze, int time);
bool NPC_GetAnimation(void *npc, int *animationId, float *delta, bool *loop, bool *lockX, bool *lockY, bool *freeze, int *time);
bool NPC_ApplyAnimation(void *npc, const char *animlib, const char *animname, float delta, bool loop, bool lockX, bool lockY, bool freeze, int time);
bool NPC_ClearAnimations(void *npc);
bool NPC_SetSpecialAction(void *npc, int action);
int NPC_GetSpecialAction(void *npc);
bool NPC_StartPlayback(void *npc, const char *recordName, bool autoUnload, float startPosX, float startPosY, float startPosZ, float startRotX, float startRotY, float startRotZ);
bool NPC_StartPlaybackEx(void *npc, int recordId, bool autoUnload, float startPosX, float startPosY, float startPosZ, float startRotX, float startRotY, float startRotZ);
bool NPC_StopPlayback(void *npc);
bool NPC_PausePlayback(void *npc, bool paused);
bool NPC_IsPlayingPlayback(void *npc);
bool NPC_IsPlaybackPaused(void *npc);
int NPC_LoadRecord(const char *filePath);
bool NPC_UnloadRecord(int recordId);
bool NPC_IsValidRecord(int recordId);
int NPC_GetRecordCount();
bool NPC_UnloadAllRecords();
bool NPC_OpenNode(int nodeId);
bool NPC_CloseNode(int nodeId);
bool NPC_IsNodeOpen(int nodeId);
int NPC_GetNodeType(int nodeId);
bool NPC_SetNodePoint(int nodeId, int pointId);
bool NPC_GetNodePointPosition(int nodeId, float *x, float *y, float *z);
int NPC_GetNodePointCount(int nodeId);
bool NPC_GetNodeInfo(int nodeId, uint32_t *vehicleNodes, uint32_t *pedNodes, uint32_t *naviNodes);
bool NPC_PlayNode(void *npc, int nodeId, int moveType, float moveSpeed, float radius, bool setAngle);
bool NPC_StopPlayingNode(void *npc);
bool NPC_PausePlayingNode(void *npc);
bool NPC_ResumePlayingNode(void *npc);
bool NPC_IsPlayingNodePaused(void *npc);
bool NPC_IsPlayingNode(void *npc);
int NPC_ChangeNode(void *npc, int nodeId, int linkId);
bool NPC_UpdateNodePoint(void *npc, int pointId);
bool NPC_SetSurfingOffset(void *npc, float x, float y, float z);
bool NPC_GetSurfingOffset(void *npc, float *x, float *y, float *z);
bool NPC_SetSurfingVehicle(void *npc, void *vehicle);
int NPC_GetSurfingVehicle(void *npc);
bool NPC_SetSurfingObject(void *npc, void *object);
int NPC_GetSurfingObject(void *npc);
bool NPC_SetSurfingPlayerObject(void *npc, void *player, int objectId);
int NPC_GetSurfingPlayerObject(void *npc);
bool NPC_ResetSurfingData(void *npc);

#endif
